### ISSUE TITLE
Big Sur pyglet error

### ISSUE THREAD

**Issue by davidADSP** [hardmaru/slimevolleygym#10]
For anyone experiencing the following error on Mac, Big Sur:

`ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.`

this fix worked for me:

https://github.com/pyglet/pyglet/issues/274#issuecomment-727584254

**Comment by hardmaru** [comment]
Hey, thanks for pointing this out.

Is there anything we can do specifically in the code to avoid the error? Or just need to wait for newer pyglet release later on.

**Comment by hardmaru** [comment]
Added a note regarding pyglet version used.
