### ISSUE TITLE
Multi-agent Extra action not working

### ISSUE THREAD

**Issue by AveryWenwenSi** [hardmaru/slimevolleygym#14]
Hi, 
Thank you so much for this beautiful environment and all the well-trained models!
May I ask a question when trying to run `python eval_agents.py --left ppo --right cma --render` where I got the error 
Traceback (most recent call last):
  File "eval_agents.py", line 174, in <module>
    render_mode=render_mode, n_trials=args.trials, init_seed=args.seed)
  File "eval_agents.py", line 93, in evaluate_multiagent
    cumulative_score = rollout(env, policy0, policy1, render_mode=render_mode)
  File "eval_agents.py", line 72, in rollout
    obs0, reward, done, info = env.step(action0, action1)
TypeError: step() takes 2 positional arguments but 3 were given

Could you please give me some advice on it? Thanks!

**Comment by hardmaru** [comment]
Hi! I added a note regarding Library Versions that this has been developed on.
