### ISSUE TITLE
Project Page Stable Baselines

### ISSUE THREAD

**Issue by araffin** [hardmaru/slimevolleygym#2]
Hello David,

Very nice project =)! I'm glab that you chose Stable Baselines for the RL part.

We would be also interested if you could do a pull request on [stable-baselines](https://github.com/hill-a/stable-baselines) where you add your project to the [documentation](https://stable-baselines.readthedocs.io/en/master/misc/projects.html) (project section) ;)

This will help people when they want to solve similar environments (e.g. self-play) and also give additional visibility to your repo ;)

**Comment by hardmaru** [comment]
Sure thing, let me do that today!
