### ISSUE TITLE
Requirement for cv2

### ISSUE THREAD

**Issue by asears** [hardmaru/slimevolleygym#4]
Cool environment! Based on one of my favs, https://g.co/kgs/c9USnV

Seems the project require opencv-python-4.2.0.34 added to setup.py?

```
python test_state.py
Traceback (most recent call last):
  File "test_state.py", line 10, in <module>
    import slimevolleygym
  File "D:\projects\python\slimevolleygym\slimevolleygym\__init__.py", line 1, in <module>
    import slimevolleygym.slimevolley
  File "D:\projects\python\slimevolleygym\slimevolleygym\slimevolley.py", line 22, in <module>
    import cv2 # installed with gym anyways
ModuleNotFoundError: No module named 'cv2'
```

```
ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2
```

**Comment by hardmaru** [comment]
Hi @asears,

My understanding is that cv2 is needed for gym to install, and that's the reason I didn't include it explicitly. is that the case?

**Comment by hardmaru** [comment]
You could be right. I looked at gym's logs, and it did seem like they removed cv2 from recent versions as a requirement in 2020 (I usually use an older version of gym).

"remove python-opencv from the requirements"

https://github.com/openai/gym

**Comment by asears** [comment]
Added #5 in case you want to fix.  Hoping to find a gym for Atari Qix!
